"""A fake ``cap1xxx`` capacitive touch controller (CAP1166).

Only the surface used by ``gfxhat.touch`` is implemented:

* event registration via :meth:`Cap1166.on`
* button LED state and global brightness
* the various configuration writes, which are accepted as no-ops

Touch events themselves are generated by the GUI, which calls into the
shared device; this class just records where the handlers should go.
"""
from .device import device


class Cap1166:
    """Stand-in for ``cap1xxx.Cap1166``."""

    def __init__(self, i2c_addr=0x2c, *args, **kwargs):
        self.i2c_addr = i2c_addr
        self._max_duty = 15

    # -- event registration ---------------------------------------------
    def on(self, channel=None, event='press', handler=None):
        """Register a handler for a channel/event pair."""
        if handler is not None:
            device.register_handler(channel, event, handler)

    # -- button LEDs -----------------------------------------------------
    def set_led_state(self, led, state):
        device.set_led(led, state)

    def set_led_linking(self, led, state):
        """No-op: link/unlink an LED from its touch input."""

    def set_led_direct_max_duty(self, duty):
        """Set the global LED duty cycle (0..15) as a brightness."""
        self._max_duty = duty
        device.set_led_brightness(duty / 15.0)

    # -- configuration (all accepted, no visible effect) -----------------
    def enable_repeat(self, mask):
        """No-op: accept the per-channel repeat mask."""

    def set_repeat_rate(self, rate):
        """No-op: accept the hold-repeat rate."""

    def _write_byte(self, register, value):
        """No-op: accept a raw register write (calibration, sensitivity)."""

    def _read_byte(self, register):
        return 0
